// Checks the hand-written ABI in src/abi.ts against the artifact generated by solc.
import { describe, expect, it } from 'vitest';
import { toEventSelector, toFunctionSelector, type AbiParameter } from 'viem';
import { deliverProofAbi } from '../src/abi.js';
import { artifact } from './hardhat-node.js';

type Item = {
  type: string;
  name?: string;
  inputs?: AbiParameter[];
  outputs?: AbiParameter[];
  stateMutability?: string;
  anonymous?: boolean;
};
const norm = (ps: readonly AbiParameter[] = []): unknown =>
  ps.map(p => ({
    name: p.name ?? '',
    type: p.type,
    indexed: (p as { indexed?: boolean }).indexed ?? false,
    components: 'components' in p ? norm(p.components) : undefined,
  }));
const key = (x: Item) => `${x.type}:${x.name ?? ''}`;
const shape = (x: Item) => ({
  type: x.type,
  name: x.name,
  inputs: norm(x.inputs),
  outputs: x.type === 'function' ? norm(x.outputs) : undefined,
  stateMutability: x.type === 'function' ? x.stateMutability : undefined,
  anonymous: x.type === 'event' ? (x.anonymous ?? false) : undefined,
});

describe('src/abi.ts ABI vs DeliverProof.sol artifact', () => {
  const compiled = artifact().abi as Item[];
  const declared = deliverProofAbi as unknown as Item[];
  it('every declared item exists in the artifact with matching types, names, indexed, mutability and selector', () => {
    for (const d of declared) {
      const c = compiled.find(x => key(x) === key(d));
      expect(c, key(d)).toBeDefined();
      expect(shape(d), key(d)).toEqual(shape(c!));
      if (d.type === 'function' || d.type === 'error')
        expect(toFunctionSelector(d as never)).toBe(toFunctionSelector(c as never));
      if (d.type === 'event') expect(toEventSelector(d as never)).toBe(toEventSelector(c as never));
    }
  });
  it('the artifact has only these extra items (no missing write function or event)', () => {
    const extra = compiled
      .filter(c => !declared.some(d => key(d) === key(c)))
      .map(key)
      .sort();
    expect(extra).toEqual([
      'constructor:',
      'fallback:',
      'function:DOMAIN',
      'function:MAX_AMOUNT_TINYBAR',
      'function:MAX_FILE_BYTES',
      'function:nextId',
      'function:totalCredits',
      'function:totalLocked',
      'receive:',
    ]);
    const missingWrites = compiled.filter(
      c =>
        (c.type === 'event' ||
          (c.type === 'function' && c.stateMutability !== 'view' && c.stateMutability !== 'pure')) &&
        !declared.some(d => key(d) === key(c)),
    );
    expect(missingWrites).toEqual([]);
  });
});
